import {ArrowLeft,CalendarDays,CheckCircle2,Clock3,MessageCircle,ShieldCheck,Star,Users,CarFront,BusFront,CarTaxiFront,Bike,QrCode,PlayCircle,Flag,Share2,UserRound,Music,Wind,MessageSquare,Dog} from "lucide-react";
import {Link,useNavigate,useParams} from "react-router-dom";
import {demoBookings,demoRides} from "../data/demo";
import {joinRide,getBookings} from "../services/api";
import {checkInPassenger,getRideCheckIns,getDriverRideCode,getRideWaitlist,joinWaitlist,getRidePreferences,getTrusted} from "../services/featureApi";
import {useAuth} from "../context/AuthContext";
import {useEffect,useState} from "react";
import Modal from "../components/Modal";
import {Booking} from "../types";

export default function RideDetails(){
 const {id}=useParams();const {user}=useAuth();const nav=useNavigate();const ride=demoRides.find(r=>r.id===id);const [modal,setModal]=useState(false);const [joined,setJoined]=useState(false);const [booking,setBooking]=useState<Booking|null>(null);const [checkCode,setCheckCode]=useState("");const [checkMsg,setCheckMsg]=useState("");const [waitMsg,setWaitMsg]=useState("");const [refresh,setRefresh]=useState(0);const [shared,setShared]=useState("");
 useEffect(()=>{if(!ride||!user)return;getBookings().then(bs=>{const b=bs.find(x=>x.rideId===ride.id&&x.status!=="cancelled");if(b){setBooking(b);setJoined(true)}})},[ride?.id,user?.id,refresh]);
 if(!ride)return <div className="page"><div className="state"><h2>Ride not found</h2><Link to="/rides" className="button button-primary">Find another ride</Link></div></div>;
 const checks=getRideCheckIns(ride.id);const wait=getRideWaitlist(ride.id);const prefs=ride.preferences||getRidePreferences(ride.id);const myCheck=booking?checks.find(x=>x.bookingId===booking.id):undefined;
 async function confirm(){try{const b=await joinRide(ride.id);setBooking(b);setJoined(true);setModal(false);setRefresh(x=>x+1)}catch(e){setCheckMsg(e instanceof Error?e.message:"Could not join ride.")}}
 async function doCheckIn(){setCheckMsg("");if(!booking)return;try{await checkInPassenger(ride.id,booking,checkCode);setCheckMsg("✓ Check-in confirmed. You are ready for the ride.");setCheckCode("");setRefresh(x=>x+1)}catch(e){setCheckMsg(e instanceof Error?e.message:"Check-in failed.")}}
 async function doWait(){try{const x=await joinWaitlist(ride.id);setWaitMsg(`You are #${x.position} on the waitlist.`)}catch(e){setWaitMsg(e instanceof Error?e.message:"Could not join waitlist.")}}
 async function shareTrip(){const text=`ICBT Carpool trip: ${ride.origin} → ${ride.destination} · ${ride.date} ${ride.time} · Driver ${ride.driver.name} · ${ride.vehicleType||"Car"}`;try{if(navigator.share)await navigator.share({title:"ICBT Carpool Trip",text});else{await navigator.clipboard?.writeText(text);setShared("Trip details copied to clipboard.")}}catch{}}
 const vehicle=ride.vehicleType==="Van"?<BusFront/>:ride.vehicleType==="Three-Wheeler"?<CarTaxiFront/>:ride.vehicleType==="Bike"?<Bike/>:<CarFront/>;
 return <div className="page"><Link to="/rides" className="back-link"><ArrowLeft size={15}/> Back to rides</Link><div className="details-grid"><main className="details-main"><div className="detail-header"><div><span className={`status status-${ride.status}`}>{ride.status.replace("_"," ")}</span><h1>{ride.origin} <span>→</span> {ride.destination}</h1><p>Ride ID: {ride.id.toUpperCase()}</p></div><div className="detail-price"><small>CONTRIBUTION</small><strong>Rs. {ride.price}</strong></div></div><div className="route-large"><div className="route-line"><span className="route-dot"/><span/><span className="route-dot destination"/></div><div><div><small>DEPARTS FROM</small><strong>{ride.origin}</strong></div><div><small>DESTINATION</small><strong>{ride.destination}</strong></div></div></div><div className="detail-meta-grid"><Meta icon={<CalendarDays/>} label="Date" value={new Date(ride.date).toLocaleDateString("en-GB",{weekday:"short",day:"2-digit",month:"long"})}/><Meta icon={<Clock3/>} label="Departure" value={ride.time}/><Meta icon={<Users/>} label="Availability" value={`${ride.seatsAvailable} of ${ride.seats} seats`}/><Meta icon={vehicle} label="Vehicle" value={ride.vehicleType||"Car"}/></div>
 <div className="detail-section"><h2>Smart match explanation</h2><div className="match-explain-grid"><div><strong>92% Excellent Match</strong><p>Route, time and availability fit your saved campus commute.</p></div><span>Pickup area <b>+40%</b></span><span>Destination <b>+30%</b></span><span>Time <b>+20%</b></span><span>Seats <b>+10%</b></span></div></div>
 <div className="detail-section"><h2>Ride preferences</h2><div className="preference-summary"><span><Music size={14}/> Music: {prefs.music}</span><span><Wind size={14}/> AC: {prefs.ac}</span><span><MessageSquare size={14}/> Chat: {prefs.conversation}</span><span><Dog size={14}/> Pets: {prefs.pets.replace("_"," ")}</span><span>🚭 Smoking: {prefs.smoking.replace("_"," ")}</span></div></div>
 <div className="detail-section"><h2>About this ride</h2><p>{ride.notes||"No additional notes."}</p><p className="muted-line"><MapPinText zone={ride.pickupZone||ride.origin}/></p></div>
 {booking&&<div className="detail-section checkin-card"><div className="section-inline"><div><span className="eyebrow">QR / CODE CHECK-IN</span><h2>Your ride check-in</h2></div><QrCode size={25}/></div>{myCheck?<div className="checked-in"><CheckCircle2/> Checked in at {new Date(myCheck.checkedInAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</div>:<><p>Ask the driver for the 4-digit ride code before pickup.</p><div className="checkin-form"><input value={checkCode} onChange={e=>setCheckCode(e.target.value)} maxLength={4} placeholder="4-digit code"/><button className="button button-primary" onClick={doCheckIn}>Check in</button></div>{checkMsg&&<div className="alert error">{checkMsg}</div>}</>}</div>}
 <div className="detail-section safety-box"><ShieldCheck size={22}/><div><h3>Trip safety</h3><p>Confirm pickup details through messaging and share only necessary personal information.</p></div></div></main>
 <aside className="details-side"><div className="driver-card"><span className="eyebrow">DRIVER TRUST PROFILE</span><div className="driver-profile"><div className="avatar xl">{ride.driver.name[0]}</div><div><h3>{ride.driver.name}</h3><span><Star size={13} fill="currentColor"/> {ride.driver.rating.toFixed(1)} rating</span></div></div><div className="trust-badges"><span>✓ ICBT Verified</span><span>✓ Phone Verified</span><span>✓ Email Verified</span></div><div className="driver-stats"><span><strong>{ride.driver.totalTrips}</strong> trips</span><span><strong>{ride.seatsAvailable}</strong> seats left</span></div><div className="trust-rate"><strong>96%</strong><small>On-time rate</small></div><Link className="button button-outline full" to={`/messages?ride=${ride.id}`}><MessageCircle size={16}/> Message driver</Link></div>{ride.status==="full"&&!joined?<><button className="button button-primary full join-button" onClick={doWait}><Flag size={16}/> Join waitlist</button>{waitMsg&&<div className="wait-message">{waitMsg}</div>}</>:<button className="button button-primary full join-button" disabled={ride.status==="completed"||ride.status==="started"||joined} onClick={()=>setModal(true)}>{joined?<><CheckCircle2 size={17}/> Confirmed</>:ride.status==="started"?<><PlayCircle size={17}/> In progress</>:ride.status==="completed"?"Completed":"Request to join"}</button>}{joined&&!myCheck&&ride.status!=="completed"&&<div className="share-trip"><div><ShieldCheck size={17}/><div><strong>Trip safety</strong><small>{getTrusted()?"Trusted contact saved":"Add a trusted contact"}</small></div></div><div className="share-actions"><button type="button" onClick={shareTrip}><Share2 size={15}/> Share trip</button><Link to="/safety"><UserRound size={15}/> Manage</Link></div></div>}{shared&&<div className="wait-message">{shared}</div>}</aside></div><Modal open={modal} title="Join this ride?" onClose={()=>setModal(false)}><p>You are requesting a seat on the <strong>{ride.time}</strong> ride from <strong>{ride.origin}</strong> to <strong>{ride.destination}</strong>.</p><div className="modal-actions"><button className="button button-outline" onClick={()=>setModal(false)}>Cancel</button><button className="button button-primary" onClick={confirm}>Confirm seat</button></div></Modal></div>
}
function Meta({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="detail-meta"><span>{icon}</span><small>{label}</small><strong>{value}</strong></div>}
function MapPinText({zone}:{zone:string}){return <span><MapPinIcon/> Pickup zone: <strong>{zone}</strong></span>}
function MapPinIcon(){return <span style={{display:"inline-block",marginRight:5}}>📍</span>}
