import {FormEvent,useState} from "react";
import {ArrowLeft,CalendarDays,CheckCircle2,Clock3,MapPin,Users,CarFront,BusFront,CarTaxiFront,Bike,Repeat2,Music,Wind,MessageCircle,Dog} from "lucide-react";
import {Link,useNavigate} from "react-router-dom";
import {createRecurringRideSeries} from "../services/api";
import {PickupZone,RidePreferences,VehicleType} from "../types";

const zones:PickupZone[]=["ICBT Main Gate","Nugegoda Junction","Maharagama","Kottawa","Dehiwala","Kaduwela","Custom Location"];
const emptyPrefs:RidePreferences={music:"no",ac:"yes",smoking:"not_allowed",conversation:"normal",pets:"not_allowed"};
export default function CreateRide(){
 const nav=useNavigate();const [f,setF]=useState({origin:"",destination:"ICBT Colombo Campus",date:"",time:"",seats:"3",price:"150",vehicleType:"Car" as VehicleType,notes:"",pickupZone:"ICBT Main Gate" as PickupZone,recurring:false,days:["Monday","Tuesday","Wednesday","Thursday","Friday"],until:"",prefs:emptyPrefs});
 const [error,setError]=useState("");const [loading,setLoading]=useState(false);const [success,setSuccess]=useState(0);const set=(k:string,v:any)=>setF(x=>({...x,[k]:v}));
 function toggleDay(day:string){set("days",f.days.includes(day)?f.days.filter(x=>x!==day):[...f.days,day])}
 async function submit(e:FormEvent){e.preventDefault();setError("");if(!f.origin||!f.destination||!f.date||!f.time)return setError("Complete route, date and departure time.");if(f.recurring&&(!f.days.length||!f.until))return setError("Choose at least one recurring day and an end date.");if(Number(f.seats)<1||Number(f.seats)>8)return setError("Seats must be between 1 and 8.");setLoading(true);try{const rides=await createRecurringRideSeries({origin:f.origin,destination:f.destination,date:f.date,time:f.time,seats:Number(f.seats),price:Number(f.price),vehicleType:f.vehicleType,notes:f.notes,pickupZone:f.pickupZone,preferences:f.prefs,recurring:f.recurring},f.recurring?f.days:[],f.recurring?f.until:f.date);setSuccess(rides.length);setTimeout(()=>nav("/driver"),700)}catch(x){setError(x instanceof Error?x.message:"Could not create ride.")}finally{setLoading(false)}}
 return <div className="page narrow-page"><Link to="/dashboard" className="back-link"><ArrowLeft size={15}/> Back to dashboard</Link><div className="page-heading"><div><span className="eyebrow">DRIVER FLOW</span><h1>Offer a ride</h1><p>Create a one-time or recurring campus journey.</p></div></div>{success>0&&<div className="alert success"><CheckCircle2 size={17}/> {success===1?"Ride published successfully.":`${success} recurring rides created successfully.`}</div>}{error&&<div className="alert error">{error}</div>}
 <form className="form-card" onSubmit={submit}>
  <Section n="01" title="ICBT pickup & route" text="Use a known campus pickup zone for safer and smarter matching."><div className="two-col"><Field label="Pickup point" icon={<MapPin/>}><input required value={f.origin} onChange={e=>set("origin",e.target.value)} placeholder="e.g. Kaduwela"/></Field><Field label="Destination" icon={<MapPin/>}><input required value={f.destination} onChange={e=>set("destination",e.target.value)}/></Field></div><label>Pickup zone<select value={f.pickupZone} onChange={e=>set("pickupZone",e.target.value)}>{zones.map(z=><option key={z}>{z}</option>)}</select></label></Section>
  <Section n="02" title="Schedule, vehicle & capacity" text="Give passengers the key details they need to plan the journey."><div className="three-col"><Field label="Date" icon={<CalendarDays/>}><input required type="date" value={f.date} onChange={e=>set("date",e.target.value)}/></Field><Field label="Departure" icon={<Clock3/>}><input required type="time" value={f.time} onChange={e=>set("time",e.target.value)}/></Field><Field label="Available seats" icon={<Users/>}><input required type="number" min="1" max="8" value={f.seats} onChange={e=>set("seats",e.target.value)}/></Field></div><div className="vehicle-field"><div className="vehicle-label">Vehicle type</div><div className="vehicle-options">{([{value:"Car",label:"Car",icon:<CarFront/>},{value:"Van",label:"Van",icon:<BusFront/>},{value:"Three-Wheeler",label:"Three-Wheeler",icon:<CarTaxiFront/>},{value:"Bike",label:"Bike",icon:<Bike/>}] as any[]).map(v=><button type="button" key={v.value} className={`vehicle-option ${f.vehicleType===v.value?"selected":""}`} onClick={()=>set("vehicleType",v.value)}>{v.icon}<span>{v.label}</span></button>)}</div></div></Section>
  <Section n="03" title="Recurring rides" text="Save time by publishing the same campus commute across multiple days."><label className="toggle-row"><input type="checkbox" checked={f.recurring} onChange={e=>set("recurring",e.target.checked)}/><span><strong>Make this a recurring ride</strong><small>Automatically create rides for the selected weekdays.</small></span><Repeat2 size={19}/></label>{f.recurring&&<div className="recurring-box"><div className="day-picker">{["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"].map(d=><button type="button" key={d} className={f.days.includes(d)?"selected":""} onClick={()=>toggleDay(d)}>{d.slice(0,3)}</button>)}</div><label>Repeat until<input type="date" required={f.recurring} value={f.until} onChange={e=>set("until",e.target.value)}/></label></div>}</Section>
  <Section n="04" title="Ride preferences" text="Passengers can use these preferences to choose a compatible ride."><div className="preference-grid"><Preference icon={<Music/>} label="Music" value={f.prefs.music} options={["yes","no"]} onChange={v=>set("prefs",{...f.prefs,music:v})}/><Preference icon={<Wind/>} label="Air conditioning" value={f.prefs.ac} options={["yes","no"]} onChange={v=>set("prefs",{...f.prefs,ac:v})}/><Preference icon={<MessageCircle/>} label="Conversation" value={f.prefs.conversation} options={["quiet","normal","social"]} onChange={v=>set("prefs",{...f.prefs,conversation:v})}/><Preference icon={<Dog/>} label="Pets" value={f.prefs.pets} options={["allowed","not_allowed"]} onChange={v=>set("prefs",{...f.prefs,pets:v})}/><Preference icon={<span>🚭</span>} label="Smoking" value={f.prefs.smoking} options={["allowed","not_allowed"]} onChange={v=>set("prefs",{...f.prefs,smoking:v})}/></div></Section>
  <Section n="05" title="Contribution & notes" text="Optional details help passengers decide quickly."><div className="two-col"><label>Suggested contribution (Rs.)<input type="number" min="0" value={f.price} onChange={e=>set("price",e.target.value)}/></label><label>Additional notes<textarea rows={4} value={f.notes} onChange={e=>set("notes",e.target.value)} placeholder="Pickup landmark, luggage information, etc."/></label></div></Section>
  <div className="form-footer"><p><strong>Privacy tip:</strong> Share only information needed for the journey.</p><button className="button button-primary" disabled={loading}>{loading?"Publishing…":f.recurring?"Create recurring rides":"Publish ride"} <CheckCircle2 size={17}/></button></div>
 </form></div>
}
function Section({n,title,text,children}:{n:string;title:string;text:string;children:React.ReactNode}){return <section className="form-section"><div className="form-section-title"><span>{n}</span><div><h2>{title}</h2><p>{text}</p></div></div>{children}</section>}
function Field({label,icon,children}:{label:string;icon:React.ReactNode;children:React.ReactNode}){return <label>{label}<div className="input-icon">{icon}{children}</div></label>}
function Preference({icon,label,value,options,onChange}:{icon:React.ReactNode;label:string;value:string;options:string[];onChange:(v:any)=>void}){return <div className="preference-card"><div className="preference-head">{icon}<strong>{label}</strong></div><div className="preference-options">{options.map(o=><button type="button" key={o} className={value===o?"selected":""} onClick={()=>onChange(o)}>{o.replace("_"," ")}</button>)}</div></div>}
