import {ArrowRight,CheckCircle2,MapPinned,ShieldCheck,Users,CarFront} from "lucide-react";
import {Link} from "react-router-dom";
export default function Landing(){
 return <div className="landing"><header className="landing-nav"><Link className="brand" to="/"><div className="brand-mark"><CarFront size={23}/></div><div><strong>ICBT</strong><span>Carpool</span></div></Link><div className="landing-links"><a href="#how">How it works</a><a href="#benefits">Benefits</a><Link to="/login">Sign in</Link><Link className="button button-primary small" to="/register">Get started</Link></div></header>
 <section className="hero"><div className="hero-copy"><span className="pill"><span className="live-dot"/> Built for ICBT students & staff</span><h1>Share the journey.<br/><span>Save fuel. Save time.</span></h1><p>Find trusted people travelling your way, join a carpool, or offer your spare seats. A simpler response to everyday commuting and fuel challenges.</p><div className="hero-actions"><Link className="button button-primary" to="/register">Start carpooling <ArrowRight size={17}/></Link><Link className="button button-ghost" to="/login">I already have an account</Link></div><div className="hero-trust"><CheckCircle2 size={16}/> Campus-focused <CheckCircle2 size={16}/> Route matching <CheckCircle2 size={16}/> Messaging</div></div><div className="hero-visual"><div className="map-card"><div className="map-grid"/><div className="road road-one"/><div className="road road-two"/><span className="map-pin pin-a">A</span><span className="map-pin pin-b">ICBT</span><div className="floating-card floating-top"><div className="avatar">K</div><div><strong>Kasun is driving</strong><small>Nugegoda → ICBT</small></div><b>07:30</b></div><div className="floating-card floating-bottom"><Users size={17}/><div><strong>2 seats left</strong><small>Tomorrow morning</small></div></div></div></div></section>
 <section className="stats-strip"><div><b>01</b><span>Find your route</span></div><div><b>02</b><span>Compare rides</span></div><div><b>03</b><span>Join the ride</span></div><div><b>04</b><span>Travel together</span></div></section>
 <section id="how" className="section"><div className="section-heading"><span className="eyebrow">HOW IT WORKS</span><h2>One clear flow from search to seat.</h2><p>Designed around the core carpooling journey.</p></div><div className="feature-grid"><Feature icon={<MapPinned/>} n="01" title="Search by route" text="Enter pickup, campus destination, date and preferred time."/><Feature icon={<Users/>} n="02" title="Compare rides" text="Review driver details, availability, contribution and timing."/><Feature icon={<ShieldCheck/>} n="03" title="Coordinate safely" text="Join a suitable ride and message participants about pickup." /></div></section>
 <section id="benefits" className="section section-soft"><div className="section-heading"><span className="eyebrow">CAMPUS EXPERIENCE</span><h2>Practical features for everyday commuting.</h2></div><div className="benefit-grid">{["Fuel-conscious","Clear availability","Connected messaging","Responsive design"].map((x,i)=><div className="benefit" key={x}><CheckCircle2 size={19}/><div><h3>{x}</h3><p>{["Shared trips can reduce duplicated journeys.","See seats, time and status before joining.","Keep ride coordination in one place.","Use the system on desktop, tablet or mobile."][i]}</p></div></div>)}</div></section>
 <footer className="landing-footer"><span>© 2026 ICBT Carpool</span><span>SEN5002 Agile Development & DevOps</span></footer></div>
}
function Feature({icon,n,title,text}:{icon:React.ReactNode;n:string;title:string;text:string}){return <div className="feature-card"><div className="feature-icon">{icon}</div><b className="feature-number">{n}</b><h3>{title}</h3><p>{text}</p></div>}
